# Generated by Django 2.1.3 on 2018-12-16 13:55

import clients.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField(default=0)),
                ('joined', models.DateField(auto_now=True)),
                ('business', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('POTENTIAL', 'POTENTIAL'), ('STALLED', 'STALLED'), ('CANCELLED', 'CANCELLED'), ('IN_DISCUSSION', 'IN_DISCUSSION'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETE', 'COMPLETE'), ('IN_UPSELL', 'IN_UPSELL')], max_length=255)),
                ('project_type', models.CharField(choices=[('WEB_APP', 'WEB_APP'), ('PWA', 'PWA'), ('DESKTOP_APP', 'DESKTOP_APP'), ('WEBSITE', 'WEBSITE'), ('SOCIAL MEDIA MANAGEMENT', 'SOCIAL MEDIA MANAGEMENT'), ('TBD', 'TBD')], default=('WEB_APP', 'WEB_APP'), max_length=255)),
                ('technology_stack', models.CharField(choices=[('DJANGO_GRAPHQL & REACT_APOLLO', 'DJANGO_GRAPHQL & REACT_APOLLO'), ('NODE.JS & REACT & ELECTRON', 'NODE.JS & REACT & ELECTRON'), ('REACT', 'REACT'), ('HTML/CSS/JS', 'HTML/CSS/JS'), ('TBD', 'TBD'), ('N/A', 'N/A')], default=('DJANGO_GRAPHQL & REACT_APOLLO', 'DJANGO_GRAPHQL & REACT_APOLLO'), max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('pivotal_tracker', models.URLField(blank=True, max_length=255, null=True)),
                ('repositories', models.TextField(blank=True, null=True)),
                ('dev_team', models.TextField(blank=True, null=True)),
                ('project_docs', models.TextField(blank=True, null=True)),
                ('total_amount', models.CharField(blank=True, max_length=255, null=True)),
                ('amount_paid', models.CharField(blank=True, max_length=255, null=True)),
                ('amount_due', models.CharField(blank=True, max_length=255, null=True)),
                ('expenditure', models.TextField(blank=True, null=True)),
                ('profit', models.TextField(blank=True, null=True)),
                ('expected_start_date', models.DateField(blank=True, null=True)),
                ('expected_duration', models.CharField(blank=True, max_length=255, null=True)),
                ('expected_end_date', models.DateField(blank=True, null=True)),
                ('actual_start_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('actual_duration', models.CharField(blank=True, max_length=255, null=True)),
                ('product_urls', models.TextField(blank=True, null=True)),
                ('project_complexity', models.IntegerField(default=0, validators=[clients.models.validate_numbers])),
                ('rate_client', models.IntegerField(default=0, validators=[clients.models.validate_numbers])),
                ('comments', models.TextField(blank=True, null=True)),
                ('rating', models.IntegerField(default=0, validators=[clients.models.validate_numbers])),
                ('feedback', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('ordering',),
            },
        ),
    ]
