# Generated by Django 2.1.3 on 2018-11-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='stack',
            field=models.CharField(choices=[('PYTHON/KIVY', 'PYTHON/KIVY'), ('NODE.JS/REACT/ELECTRON', 'NODE.JS/REACT/ELECTRON'), ('DJANGO', 'DJANGO'), ('DRF/REACT', 'DRF/REACT'), ('FLASK', 'FLASK'), ('N/A', 'N/A'), ('TBD', 'TBD'), ('REACT', 'REACT'), ('HTML/CSS/JS', 'HTML/CSS/JS')], max_length=255),
        ),
    ]
